apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: custom-airbyte-volume-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: ebs-sc