apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: fe-deployments-stack
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
        - variant: grafana-dashboard
          label: prometheus-grafana-crds
          filename: airflow-dashboard
          namespace: monitoring
        - variant: airflow-statsd
          label: prometheus-grafana-crds
          filename: prometheus-servicemonitor
          namespace: monitoring
        # - variant: forge
          # label: elite-airflow
          # path: elite-airflow
        #   namespace: forge-airflow
  template:
    metadata:
      name: '{{.variant}}'
      labels:
        name: '{{.label}}'
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default

      source:
        repoURL: https://github.com/Federated-Engineers/kubernetes-deployments.git
        targetRevision: appset-test
        path: 
        - application-deployments/deployments/{{.filename}}.yaml
    
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.namespace}}'
        
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
        - CreateNamespace=true
        - ApplyOutofSyncOnly=true